### ISSUE TITLE
Unable to stat files with UTF characters

### ISSUE THREAD

**Issue by DanielThomas** [adammurdoch/native-platform#28]
We ran into a project with a file with an emoji filename (no really), and looks like `stat` chokes:

```
Caused by: net.rubygrapefruit.platform.NativeException: Could not get UNIX mode on /mnt/builds/slave/workspace/project/src/node_modules/.bin/🐹: file does not exist.
	at net.rubygrapefruit.platform.internal.DefaultPosixFiles.getMode(DefaultPosixFiles.java:68)
	at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedStat.getUnixMode(NativePlatformBackedStat.java:34)
	at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.getUnixMode(GenericFileSystem.java:74)
	... 83 more
```

I'd guess if this affects emojis, it might affect any file UTF-8 characters?

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.

***

Some related work was done in
* https://github.com/gradle/native-platform/pull/32

We tested it with the latest version of Gradle (9.1.0) and it fails:

```
$ touch lib/src/main/resources/🐹.txt
$ gradle build
Calculating task graph as no cached configuration is available for tasks: build
> Task :lib:processResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:processResources'.
> Could not copy file '.../test/lib/src/main/resources/🐹.txt' to '.../test/lib/build/resources/main/🐹.txt'.
   > Could not get file mode for '.../test/lib/src/main/resources/🐹.txt'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to generate a Build Scan (Powered by Develocity).
> Get more help at https://help.gradle.org.

BUILD FAILED in 10s
2 actionable tasks: 2 executed
Configuration cache entry stored.
```
